apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: buildbot-worker
  name: buildbot-worker
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: buildbot-worker
  template:
    metadata:
      labels:
        k8s-app: buildbot-worker
    spec:
      containers:
      - name: buildbot-worker
        image: buildbot/buildbot-worker:master
        env:
        - name: BUILDMASTER
          value: buildbot
        - name: BUILDMASTER_PORT
          value: "9989"
        - name: WORKERNAME
          value: cite-build01-01
        - name: WORKERPASS
          value: cite-buildbot-worker
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: docker-binary
          mountPath: /usr/bin/docker
        securityContext:
          privileged: true
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: docker-binary
          hostPath:
            path: /usr/bin/docker
